export {
  booleanAttributes,
  commentNode,
  fragments,
  html,
  isCommentNode,
  isElementNode,
  isTextNode,
  Kind,
  type MCommentNode,
  type MElement,
  type MFragment,
  type MNode,
  type MSpacesAndComments,
  type MTextNode,
  type SerializationOptions,
  serializeFragments,
  serializeNode,
  shadowRoot,
  textNode,
} from "./parser.ts";
