export { type Parser } from "@fcrozatier/monarch";
export {
  booleanAttributes,
  commentNode,
  element,
  ElementKind as Kind,
  fragments,
  html,
  isCommentNode,
  isElementNode,
  isMNode,
  isTextNode,
  type MCommentNode,
  type MElement,
  type MFragment,
  type MNode,
  type MSpacesAndComments,
  type MTextNode,
  type SerializationOptions,
  serializeFragments,
  serializeNode,
  shadowRoot,
  textNode,
} from "./parser.ts";
